// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// The admin console is a web app only.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError('PaddlerBites Admin runs on the web only. Use `flutter run -d chrome`.');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5S484Nc_qgcJAupAUmAmkzsAETCDLXCE',
    appId: '1:1049652420108:web:14e83225e349a7b81c9829',
    messagingSenderId: '1049652420108',
    projectId: 'paddlerbites-1453d',
    authDomain: 'paddlerbites-1453d.firebaseapp.com',
    storageBucket: 'paddlerbites-1453d.firebasestorage.app',
    measurementId: 'G-E3TTWL6VCD',
  );
}
